### ISSUE TITLE
Agregar horario de control para establecer horarios de trabajo

### ISSUE THREAD

**Issue by jignaciol** [sistemashcapp/HCNotificadorHRIS#18]

**Comment by foxcarlos** [comment]
No entiendo este issue

**Comment by jignaciol** [comment]
es para hacer que el programa deje de enviar mensajes fuera del horario de trabajo. porque aveces se envian recordatorios y ya el soportista no esta en el hospital por lo que se pierde ese mensajes y al otro dia no envia mas recordatorios.

**Comment by jignaciol** [comment]
lo solucione por ahora colocando una comparacion adicional en el inicio del bucle while

ademas de True
la variable now debe ser mayor a 7 y menor a 17

**Comment by jignaciol** [comment]
agregue tambien la verificacion del dia de la semana para que solo envie de lunes a viernes. esto deberia desaparecer si se decide colocar la opcion de creacion de ticket al usuario
